/**
 * This class is generated by jOOQ
 */
package com.caiyunworks.example.h2.tables.daos;


import com.caiyunworks.example.h2.tables.Author;
import com.caiyunworks.example.h2.tables.records.AuthorRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorDao extends DAOImpl<AuthorRecord, com.caiyunworks.example.h2.tables.pojos.Author, Integer> {

	/**
	 * Create a new AuthorDao without any configuration
	 */
	public AuthorDao() {
		super(Author.AUTHOR, com.caiyunworks.example.h2.tables.pojos.Author.class);
	}

	/**
	 * Create a new AuthorDao with an attached configuration
	 */
	public AuthorDao(Configuration configuration) {
		super(Author.AUTHOR, com.caiyunworks.example.h2.tables.pojos.Author.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(com.caiyunworks.example.h2.tables.pojos.Author object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Author> fetchById(Integer... values) {
		return fetch(Author.AUTHOR.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public com.caiyunworks.example.h2.tables.pojos.Author fetchOneById(Integer value) {
		return fetchOne(Author.AUTHOR.ID, value);
	}

	/**
	 * Fetch records that have <code>FIRST_NAME IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Author> fetchByFirstName(String... values) {
		return fetch(Author.AUTHOR.FIRST_NAME, values);
	}

	/**
	 * Fetch records that have <code>LAST_NAME IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Author> fetchByLastName(String... values) {
		return fetch(Author.AUTHOR.LAST_NAME, values);
	}

	/**
	 * Fetch records that have <code>DATE_OF_BIRTH IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Author> fetchByDateOfBirth(Timestamp... values) {
		return fetch(Author.AUTHOR.DATE_OF_BIRTH, values);
	}

	/**
	 * Fetch records that have <code>YEAR_OF_BIRTH IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Author> fetchByYearOfBirth(Integer... values) {
		return fetch(Author.AUTHOR.YEAR_OF_BIRTH, values);
	}

	/**
	 * Fetch records that have <code>ADDRESS IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Author> fetchByAddress(String... values) {
		return fetch(Author.AUTHOR.ADDRESS, values);
	}
}
