/**
 * This class is generated by jOOQ
 */
package com.caiyunworks.example.h2.tables.daos;


import com.caiyunworks.example.h2.tables.Book;
import com.caiyunworks.example.h2.tables.records.BookRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookDao extends DAOImpl<BookRecord, com.caiyunworks.example.h2.tables.pojos.Book, Integer> {

	/**
	 * Create a new BookDao without any configuration
	 */
	public BookDao() {
		super(Book.BOOK, com.caiyunworks.example.h2.tables.pojos.Book.class);
	}

	/**
	 * Create a new BookDao with an attached configuration
	 */
	public BookDao(Configuration configuration) {
		super(Book.BOOK, com.caiyunworks.example.h2.tables.pojos.Book.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected  Integer getId(com.caiyunworks.example.h2.tables.pojos.Book object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchById(Integer... values) {
		return fetch(Book.BOOK.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public com.caiyunworks.example.h2.tables.pojos.Book fetchOneById(Integer value) {
		return fetchOne(Book.BOOK.ID, value);
	}

	/**
	 * Fetch records that have <code>AUTHOR_ID IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByAuthorId(Integer... values) {
		return fetch(Book.BOOK.AUTHOR_ID, values);
	}

	/**
	 * Fetch records that have <code>CO_AUTHOR_ID IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByCoAuthorId(Integer... values) {
		return fetch(Book.BOOK.CO_AUTHOR_ID, values);
	}

	/**
	 * Fetch records that have <code>DETAILS_ID IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByDetailsId(Integer... values) {
		return fetch(Book.BOOK.DETAILS_ID, values);
	}

	/**
	 * Fetch records that have <code>TITLE IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByTitle(String... values) {
		return fetch(Book.BOOK.TITLE, values);
	}

	/**
	 * Fetch records that have <code>PUBLISHED_IN IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByPublishedIn(Integer... values) {
		return fetch(Book.BOOK.PUBLISHED_IN, values);
	}

	/**
	 * Fetch records that have <code>LANGUAGE_ID IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByLanguageId(Integer... values) {
		return fetch(Book.BOOK.LANGUAGE_ID, values);
	}

	/**
	 * Fetch records that have <code>CONTENT_TEXT IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByContentText(String... values) {
		return fetch(Book.BOOK.CONTENT_TEXT, values);
	}

	/**
	 * Fetch records that have <code>CONTENT_PDF IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByContentPdf(byte[]... values) {
		return fetch(Book.BOOK.CONTENT_PDF, values);
	}

	/**
	 * Fetch records that have <code>REC_VERSION IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByRecVersion(Integer... values) {
		return fetch(Book.BOOK.REC_VERSION, values);
	}

	/**
	 * Fetch records that have <code>REC_TIMESTAMP IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.Book> fetchByRecTimestamp(Timestamp... values) {
		return fetch(Book.BOOK.REC_TIMESTAMP, values);
	}
}
