/**
 * This class is generated by jOOQ
 */
package com.caiyunworks.example.h2.tables.daos;


import com.caiyunworks.example.h2.tables.BookToBookStore;
import com.caiyunworks.example.h2.tables.records.BookToBookStoreRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookToBookStoreDao extends DAOImpl<BookToBookStoreRecord, com.caiyunworks.example.h2.tables.pojos.BookToBookStore, Record2<String, Integer>> {

	/**
	 * Create a new BookToBookStoreDao without any configuration
	 */
	public BookToBookStoreDao() {
		super(BookToBookStore.BOOK_TO_BOOK_STORE, com.caiyunworks.example.h2.tables.pojos.BookToBookStore.class);
	}

	/**
	 * Create a new BookToBookStoreDao with an attached configuration
	 */
	public BookToBookStoreDao(Configuration configuration) {
		super(BookToBookStore.BOOK_TO_BOOK_STORE, com.caiyunworks.example.h2.tables.pojos.BookToBookStore.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Record2<String, Integer> getId(com.caiyunworks.example.h2.tables.pojos.BookToBookStore object) {
		return compositeKeyRecord(object.getBookStoreName(), object.getBookId());
	}

	/**
	 * Fetch records that have <code>BOOK_STORE_NAME IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.BookToBookStore> fetchByBookStoreName(String... values) {
		return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_STORE_NAME, values);
	}

	/**
	 * Fetch records that have <code>BOOK_ID IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.BookToBookStore> fetchByBookId(Integer... values) {
		return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID, values);
	}

	/**
	 * Fetch records that have <code>STOCK IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.BookToBookStore> fetchByStock(Integer... values) {
		return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.STOCK, values);
	}
}
