/**
 * This class is generated by jOOQ
 */
package com.caiyunworks.example.h2.tables.daos;


import com.caiyunworks.example.h2.tables.BookStore;
import com.caiyunworks.example.h2.tables.records.BookStoreRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookStoreDao extends DAOImpl<BookStoreRecord, com.caiyunworks.example.h2.tables.pojos.BookStore, String> {

	/**
	 * Create a new BookStoreDao without any configuration
	 */
	public BookStoreDao() {
		super(BookStore.BOOK_STORE, com.caiyunworks.example.h2.tables.pojos.BookStore.class);
	}

	/**
	 * Create a new BookStoreDao with an attached configuration
	 */
	public BookStoreDao(Configuration configuration) {
		super(BookStore.BOOK_STORE, com.caiyunworks.example.h2.tables.pojos.BookStore.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected String getId(com.caiyunworks.example.h2.tables.pojos.BookStore object) {
		return object.getName();
	}

	/**
	 * Fetch records that have <code>NAME IN (values)</code>
	 */
	public List<com.caiyunworks.example.h2.tables.pojos.BookStore> fetchByName(String... values) {
		return fetch(BookStore.BOOK_STORE.NAME, values);
	}

	/**
	 * Fetch a unique record that has <code>NAME = value</code>
	 */
	public com.caiyunworks.example.h2.tables.pojos.BookStore fetchOneByName(String value) {
		return fetchOne(BookStore.BOOK_STORE.NAME, value);
	}
}
