/**
 * This class is generated by jOOQ
 */
package com.caiyunworks.example.h2.tables;


import com.caiyunworks.example.h2.Keys;
import com.caiyunworks.example.h2.Public;
import com.caiyunworks.example.h2.tables.records.BookStoreRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookStore extends TableImpl<BookStoreRecord> {

	private static final long serialVersionUID = -983097707;

	/**
	 * The reference instance of <code>PUBLIC.BOOK_STORE</code>
	 */
	public static final BookStore BOOK_STORE = new BookStore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BookStoreRecord> getRecordType() {
		return BookStoreRecord.class;
	}

	/**
	 * The column <code>PUBLIC.BOOK_STORE.NAME</code>.
	 */
	public final TableField<BookStoreRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.BOOK_STORE</code> table reference
	 */
	public BookStore() {
		this("BOOK_STORE", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.BOOK_STORE</code> table reference
	 */
	public BookStore(String alias) {
		this(alias, BOOK_STORE);
	}

	private BookStore(String alias, Table<BookStoreRecord> aliased) {
		this(alias, aliased, null);
	}

	private BookStore(String alias, Table<BookStoreRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<BookStoreRecord> getPrimaryKey() {
		return Keys.UK_T_BOOK_STORE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<BookStoreRecord>> getKeys() {
		return Arrays.<UniqueKey<BookStoreRecord>>asList(Keys.UK_T_BOOK_STORE_NAME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookStore as(String alias) {
		return new BookStore(alias, this);
	}

	/**
	 * Rename this table
	 */
	public BookStore rename(String name) {
		return new BookStore(name, null);
	}
}
