/**
 * This class is generated by jOOQ
 */
package com.caiyunworks.example.h2;


import com.caiyunworks.example.h2.tables.Author;
import com.caiyunworks.example.h2.tables.Book;
import com.caiyunworks.example.h2.tables.BookStore;
import com.caiyunworks.example.h2.tables.BookToBookStore;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.AUTHOR
	 */
	public static final Author AUTHOR = com.caiyunworks.example.h2.tables.Author.AUTHOR;

	/**
	 * The table PUBLIC.BOOK
	 */
	public static final Book BOOK = com.caiyunworks.example.h2.tables.Book.BOOK;

	/**
	 * The table PUBLIC.BOOK_STORE
	 */
	public static final BookStore BOOK_STORE = com.caiyunworks.example.h2.tables.BookStore.BOOK_STORE;

	/**
	 * The table PUBLIC.BOOK_TO_BOOK_STORE
	 */
	public static final BookToBookStore BOOK_TO_BOOK_STORE = com.caiyunworks.example.h2.tables.BookToBookStore.BOOK_TO_BOOK_STORE;
}
